### ISSUE TITLE
Add moments layer

### ISSUE THREAD

**Issue by jlperla** [HighDimensionalEconLab/econ_layers#41]
A layer that takes `R^1 -> R^M` for the first `M` moments.  Can get fancy later by making it work for things other than one dimenionslon inputs and for picking specific moments

```python
class Moments(nn.Module):
    def __init__(
        self,
        n_moments: int,
    ):
    def forward(self, input):
        return torch.cat([input.pow(m) for m in torch.range(1, self.num_moments)], 1) # or something like that.
```
A few things:
- Note that this has no learnable parameters.
- Make sure to test it with dispatching over a batch in the typical way required for the symmetry paper.

After that you can use this in a configuation file like
```yaml
model:
  phi:
    class_path: econ_layers.layers.Moments
    init_args:
      n_moments: 3
```
@jbrightuniverse  @arnavs
